### ISSUE TITLE
A percent sign breaks your service, sometimes.

### ISSUE THREAD

**Issue by sentientmachine** [chubin/cheat.sh#183]
## Todo

* [ ] Add special parameter `q` for queries, that can be used with `--data-urlencode`
* [x] Add parameters `answer` and `question` to specify them explicitly
* [ ] Add support of `q` into the cht.sh command line client

## Details

I was doing a search over your curl service for query, trying to untangle a `printf %s` for bash question, which seemed a reasonable query.  I get an nginx failure: `400 Bad Request nginx/1.13.12`

For example this query produces an error:
https://cheat.sh/python/print%20%s

But these work fine:
http://cht.sh/python/%
https://cheat.sh/python3/print%20list
http://cht.sh/python/printf%20%25s

The last one was what I intended.  Percent signs appear to be interpreted in transit between curl and nginx server side URL rewriting.  Your server says eh bro that's not a valid URL, barf.

https://www.w3schools.com/tags/ref_urlencode.ASP

But curl works fine on the terminal, showing me that maybe the problem's on client side, as long as URL encoding is done in a way that makes your server happy, then all is well?

```
$ curl cht.sh/bash/printf %s
# bash - SPRINTF in shell scripting?
var=$(printf 'FILE=_%s_%s.dat' "$val1" "$val2")
...
```
This
http://cht.sh/python/printf?myparameter#myhash
only searches for printf

One answer is: "It's the user's responsibility to url-encode all queries so nginx is happy, and take care not to search for slashes, questionmarks, percent signs or any URL escape chars".  Is this the case or is there a cleverer solution for me to pass you a literal string over curl?

**Comment by chubin** [comment]
Hi Eric, 

it is clear why it happens; indeed: nginx tries to interpret the incoming query, before passing it to the cheat.sh server, and it can't interpret the `%s`, because it does not conform to URL encoding rules, and so it is a bad request indeed.

Of course, we could just silently pass such queries to the server and make it interpret them on their own, but I am not sure that it would be good idea:

1. it would break compatibility with proxies etc.
2. there will be some characters that can't be passed directly, so they need to be escaped somehow anyway

So I would say, that yes, it the user's responsibility to use correct URLs in queries.

`curl` can't encode URL-string (as far as I know), but it can encode GET-parameters.
What should be probably done in this case, and what could be a great solution,
is to add a new parameter (e.g. `q=`), that would be interpreted as the query on the server side,
so the call would look like:
```
curl -G --data-urlencode cht.sh "q=print %s"
```
That would guarantee that everything is encoded correctly.

```
$ curl -IGv cheat.sh/ --data-urlencode "q=print %s" 2>&1 | grep HEAD
> HEAD /?q=print%20%25s HTTP/1.1
```

I think, that would be the best solution.
What do you think?

PS. Regarding this:
```
curl cht.sh/bash/printf %s
```

I don't think it worked like you wanted it. I believe, curl has interpreted it as 
a sequence of 2 urls (you can call curl with several URLs and they will be queried sequentially), and the second one (`%s`) was ignored (may be with a warning or error message), and it looked like the query was processed correctly, but it was not

**Comment by sentientmachine** [comment]
Ok, so it can't be helped.  Any query with percent signs, colons, questionmarks, hashtags, forward slashes, dots, or any other character that has a meaning as a URL, will cause nginx to puke a 400 bad request.  

Which means it's my responsibility to URL-encode my query.  Somehow I just have to know which flavor of url-encoding I ought to use so that nginx does the right thing for any of the characters: `~!@#$%^&*()_+-{}[]\|<>,./` as they descend and ascend through your service.

**Comment by chubin** [comment]
Probably, it would be better to add several additional parameters, like `question`, `answer` and already mentioned `q`, so that your query could be written like: `?q=rmse/0/1`

So, that means, the following should be done:

* [ ] Add special parameter `q` for queries, that can be used with `--data-urlencode`
* [ ] Add support of `q` into the cht.sh command line client
* [ ] Add parameters `answer` and `question` to specify them explicitly

**Comment by sentientmachine** [comment]
I'm using curl under the hood in vim, and the two lines that do the work is this:            
```
let language_name = "python"
let cht_translated_user_query = "print %s"
let cht_supplemental_parameters = "/0/1"
let cht_hit_bash_expression = "curl cht.sh/" . language_name . "/" . cht_translated_user_query . cht_supplemental_parameters . "?T 2>/dev/null"
let cht_stdout_response = system(cht_hit_bash_expression)
```

I tried url-encoding the`cht_translated_user_query` variable, thinking then it'll just work ™️ But I think somewhere between nginx url rewriting and your software the percent signs get ignored.

Your proposal of: 
```
curl -G --data-urlencode cht.sh "q=print %s"
```
Would be perfect for me because then it's a one line fix for me.

This isn't a deal breaker.  Normally I can be cleverer with my queries by saying: `"print with the hash tag format"` query rather than `print %d format` or `print %25 format` 

Maybe an even better option is for you to make a secondary API handle where I can do a POST and send you a package of json.  Then the user query doesn't have to pass through the pinhole of apache/nginx url rewriting.

**Comment by chubin** [comment]
I think that the `q=` parameter will be enough, because everything can be encoded using the standard URL-encoding.

I have a side question:
are you aware of the cheat.sh vim plugin (https://github.com/dbeniamine/cheat.sh-vim)
by @dbeniamine 

Have you tried it? What features are missing there?

When you are querying cheat.sh from Vim, how exactly you do it? You write a query, and then you press some magic key? And what happens next? The answer is pasted into the current buffer, is shown in a new buffer, or just printed in the background?

**Comment by sentientmachine** [comment]
I am aware of the other plugin, I see the it uses the terminal in the same way I do to pass the user query, yours uses `systemlist(curl)` from:
https://github.com/dbeniamine/cheat.sh-vim/blob/master/autoload/cheat.vim

Here's the jist of how I do it.  I collect up the language and user query and the output of curl gets saved to a rolling history (I save all snippets) and stamped into a new file under /tmp/userquery and I open it in a new vim tab and assert filetype, that way I can use the `hjkl` and navigation keys to edit the response as I need and stamp it as a new snippet, then run it in place with a keystroke:
https://gist.github.com/sentientmachine/e09ea2ffa50bfb6444fdd18deda07053

the cheat.sh vim plugin suffers from the same problem mine does, it uses: `curl --silent  'https://cht.sh/language/stuff+print/0/0,0?q'`
Which produces all the same errors mentioned at top, because `?`, `#`, `/` and others have special meaning to the nginx mod_rewrite url decoder.  

It's not the end of the world, the service is still delightful.  The missing feature is a way to pass language, query, parameters to curl, so that all these characters `~!@#$%^&*()_+-{}[]\|<>,./` aren't intercepted and cause an error.

If there's easy alternative way to query your service like `curl  https://cht.sh/language/userquery/0/0,0?` but where the userquery is url-encoded, I'd like to hear, but it sounds like new functionality would have to be written.

**Comment by sentientmachine** [comment]
I'm satisfied with the fixes for certain characters like percent signs, this now works as I expect on my terminal:
`curl cht.sh/bash/printf %s`
Marking as both resolved and closed.

**Comment by chubin** [comment]
but I think it still would be great to have a special query like discussed above (i.e. `q=`)
